// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"
	dto "templatev25/internal/http/dto"

	mock "github.com/stretchr/testify/mock"
)

// ActionRepository is an autogenerated mock type for the ActionRepository type
type ActionRepository struct {
	mock.Mock
}

// ByID provides a mock function with given fields: ctx, id
func (_m *ActionRepository) ByID(ctx context.Context, id int64) (domain.Action, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.Action
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Action, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Action); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Action)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, m
func (_m *ActionRepository) Create(ctx context.Context, m domain.Action) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Action) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ActionRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, q
func (_m *ActionRepository) List(ctx context.Context, q dto.ActionQuery) ([]domain.Action, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Action
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ActionQuery) ([]domain.Action, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ActionQuery) []domain.Action); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Action)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ActionQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.ActionQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.ActionQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.ActionQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *ActionRepository) Update(ctx context.Context, id int64, m domain.Action) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Action) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewActionRepository creates a new instance of ActionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActionRepository {
	mock := &ActionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
