// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"
	dto "templatev25/internal/http/dto"

	mock "github.com/stretchr/testify/mock"
)

// APILogRepository is an autogenerated mock type for the APILogRepository type
type APILogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, log
func (_m *APILogRepository) Create(ctx context.Context, log domain.APILog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.APILog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, q
func (_m *APILogRepository) List(ctx context.Context, q dto.APILogListQuery) ([]domain.APILog, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.APILog
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.APILogListQuery) ([]domain.APILog, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.APILogListQuery) []domain.APILog); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.APILog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.APILogListQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.APILogListQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.APILogListQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.APILogListQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// NewAPILogRepository creates a new instance of APILogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPILogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *APILogRepository {
	mock := &APILogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
