// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AppServiceIconGroupRepository is an autogenerated mock type for the AppServiceIconGroupRepository type
type AppServiceIconGroupRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, m
func (_m *AppServiceIconGroupRepository) Create(ctx context.Context, m domain.AppServiceIconGroup) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AppServiceIconGroup) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSoft provides a mock function with given fields: ctx, id
func (_m *AppServiceIconGroupRepository) DeleteSoft(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSoft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx
func (_m *AppServiceIconGroupRepository) List(ctx context.Context) ([]domain.AppServiceIconGroup, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.AppServiceIconGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.AppServiceIconGroup, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.AppServiceIconGroup); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AppServiceIconGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGroupsWithIcons provides a mock function with given fields: ctx
func (_m *AppServiceIconGroupRepository) ListGroupsWithIcons(ctx context.Context) ([]domain.AppServiceIconGroup, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupsWithIcons")
	}

	var r0 []domain.AppServiceIconGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.AppServiceIconGroup, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.AppServiceIconGroup); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AppServiceIconGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *AppServiceIconGroupRepository) Update(ctx context.Context, id int, m domain.AppServiceIconGroup) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.AppServiceIconGroup) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAppServiceIconGroupRepository creates a new instance of AppServiceIconGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppServiceIconGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppServiceIconGroupRepository {
	mock := &AppServiceIconGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
