// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"
	dto "templatev25/internal/http/dto"

	mock "github.com/stretchr/testify/mock"
)

// MenuRepository is an autogenerated mock type for the MenuRepository type
type MenuRepository struct {
	mock.Mock
}

// ByID provides a mock function with given fields: ctx, id
func (_m *MenuRepository) ByID(ctx context.Context, id int64) (domain.Menu, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.Menu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Menu, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Menu); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Menu)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, m
func (_m *MenuRepository) Create(ctx context.Context, m domain.Menu) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Menu) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MenuRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMenusByIDs provides a mock function with given fields: ctx, ids
func (_m *MenuRepository) GetMenusByIDs(ctx context.Context, ids []int64) ([]domain.Menu, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetMenusByIDs")
	}

	var r0 []domain.Menu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]domain.Menu, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []domain.Menu); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Menu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMenusByPermissionIDs provides a mock function with given fields: ctx, permissionIDs
func (_m *MenuRepository) GetMenusByPermissionIDs(ctx context.Context, permissionIDs []int) ([]domain.Menu, error) {
	ret := _m.Called(ctx, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMenusByPermissionIDs")
	}

	var r0 []domain.Menu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) ([]domain.Menu, error)); ok {
		return rf(ctx, permissionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) []domain.Menu); ok {
		r0 = rf(ctx, permissionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Menu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, permissionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, q
func (_m *MenuRepository) List(ctx context.Context, q dto.MenuListQuery) ([]domain.Menu, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Menu
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.MenuListQuery) ([]domain.Menu, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.MenuListQuery) []domain.Menu); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Menu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.MenuListQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.MenuListQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.MenuListQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.MenuListQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// ListAll provides a mock function with given fields: ctx
func (_m *MenuRepository) ListAll(ctx context.Context) ([]domain.Menu, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []domain.Menu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Menu, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Menu); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Menu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserRoles provides a mock function with given fields: ctx, userID
func (_m *MenuRepository) ListByUserRoles(ctx context.Context, userID int) ([]domain.Menu, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserRoles")
	}

	var r0 []domain.Menu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.Menu, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.Menu); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Menu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *MenuRepository) Update(ctx context.Context, id int64, m domain.Menu) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Menu) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMenuRepository creates a new instance of MenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MenuRepository {
	mock := &MenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
