// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	common "git.gerege.mn/backend-packages/common"

	domain "templatev25/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// AllUserIDs provides a mock function with given fields: ctx
func (_m *NotificationRepository) AllUserIDs(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllUserIDs")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateGroup provides a mock function with given fields: ctx, g
func (_m *NotificationRepository) CreateGroup(ctx context.Context, g domain.NotificationGroup) (domain.NotificationGroup, error) {
	ret := _m.Called(ctx, g)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 domain.NotificationGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationGroup) (domain.NotificationGroup, error)); ok {
		return rf(ctx, g)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationGroup) domain.NotificationGroup); ok {
		r0 = rf(ctx, g)
	} else {
		r0 = ret.Get(0).(domain.NotificationGroup)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NotificationGroup) error); ok {
		r1 = rf(ctx, g)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNotification provides a mock function with given fields: ctx, n
func (_m *NotificationRepository) CreateNotification(ctx context.Context, n domain.Notification) (domain.Notification, error) {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification) (domain.Notification, error)); ok {
		return rf(ctx, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification) domain.Notification); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Get(0).(domain.Notification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Notification) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNotificationsBulk provides a mock function with given fields: ctx, ns
func (_m *NotificationRepository) CreateNotificationsBulk(ctx context.Context, ns []domain.Notification) error {
	ret := _m.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationsBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Notification) error); ok {
		r0 = rf(ctx, ns)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByUser provides a mock function with given fields: ctx, userID, p
func (_m *NotificationRepository) ListByUser(ctx context.Context, userID int, p common.PaginationQuery) ([]domain.Notification, int64, int, int, error) {
	ret := _m.Called(ctx, userID, p)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []domain.Notification
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, int, common.PaginationQuery) ([]domain.Notification, int64, int, int, error)); ok {
		return rf(ctx, userID, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, common.PaginationQuery) []domain.Notification); ok {
		r0 = rf(ctx, userID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, common.PaginationQuery) int64); ok {
		r1 = rf(ctx, userID, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, common.PaginationQuery) int); ok {
		r2 = rf(ctx, userID, p)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, int, common.PaginationQuery) int); ok {
		r3 = rf(ctx, userID, p)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, int, common.PaginationQuery) error); ok {
		r4 = rf(ctx, userID, p)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// ListGroups provides a mock function with given fields: ctx, p
func (_m *NotificationRepository) ListGroups(ctx context.Context, p common.PaginationQuery) ([]domain.NotificationGroup, int64, int, int, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 []domain.NotificationGroup
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) ([]domain.NotificationGroup, int64, int, int, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) []domain.NotificationGroup); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotificationGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.PaginationQuery) int64); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.PaginationQuery) int); ok {
		r2 = rf(ctx, p)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, common.PaginationQuery) int); ok {
		r3 = rf(ctx, p)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, common.PaginationQuery) error); ok {
		r4 = rf(ctx, p)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *NotificationRepository) MarkAllRead(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkGroupRead provides a mock function with given fields: ctx, userID, groupID
func (_m *NotificationRepository) MarkGroupRead(ctx context.Context, userID int, groupID int) error {
	ret := _m.Called(ctx, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for MarkGroupRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
