// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	common "git.gerege.mn/backend-packages/common"

	domain "templatev25/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type OrganizationRepository struct {
	mock.Mock
}

// ByID provides a mock function with given fields: ctx, id
func (_m *OrganizationRepository) ByID(ctx context.Context, id int) (domain.Organization, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Organization, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Organization); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, m
func (_m *OrganizationRepository) Create(ctx context.Context, m domain.Organization) (domain.Organization, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Organization) (domain.Organization, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Organization) domain.Organization); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Get(0).(domain.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Organization) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OrganizationRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, p
func (_m *OrganizationRepository) List(ctx context.Context, p common.PaginationQuery) ([]domain.Organization, int64, int, int, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Organization
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) ([]domain.Organization, int64, int, int, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) []domain.Organization); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.PaginationQuery) int64); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.PaginationQuery) int); ok {
		r2 = rf(ctx, p)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, common.PaginationQuery) int); ok {
		r3 = rf(ctx, p)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, common.PaginationQuery) error); ok {
		r4 = rf(ctx, p)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Tree provides a mock function with given fields: ctx, rootID
func (_m *OrganizationRepository) Tree(ctx context.Context, rootID int) ([]domain.Organization, error) {
	ret := _m.Called(ctx, rootID)

	if len(ret) == 0 {
		panic("no return value specified for Tree")
	}

	var r0 []domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.Organization, error)); ok {
		return rf(ctx, rootID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.Organization); ok {
		r0 = rf(ctx, rootID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, rootID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *OrganizationRepository) Update(ctx context.Context, id int, m domain.Organization) (domain.Organization, error) {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Organization) (domain.Organization, error)); ok {
		return rf(ctx, id, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Organization) domain.Organization); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Get(0).(domain.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, domain.Organization) error); ok {
		r1 = rf(ctx, id, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizationRepository creates a new instance of OrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationRepository {
	mock := &OrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
