// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	common "git.gerege.mn/backend-packages/common"

	domain "templatev25/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrganizationTypeRepository is an autogenerated mock type for the OrganizationTypeRepository type
type OrganizationTypeRepository struct {
	mock.Mock
}

// AddRoles provides a mock function with given fields: ctx, orgTypeID, roleIDs
func (_m *OrganizationTypeRepository) AddRoles(ctx context.Context, orgTypeID int, roleIDs []int) error {
	ret := _m.Called(ctx, orgTypeID, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddRoles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, orgTypeID, roleIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddSystems provides a mock function with given fields: ctx, orgTypeID, systemIDs
func (_m *OrganizationTypeRepository) AddSystems(ctx context.Context, orgTypeID int, systemIDs []int) error {
	ret := _m.Called(ctx, orgTypeID, systemIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddSystems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, orgTypeID, systemIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, m
func (_m *OrganizationTypeRepository) Create(ctx context.Context, m domain.OrganizationType) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrganizationType) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OrganizationTypeRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, p
func (_m *OrganizationTypeRepository) List(ctx context.Context, p common.PaginationQuery) ([]domain.OrganizationType, int64, int, int, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.OrganizationType
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) ([]domain.OrganizationType, int64, int, int, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) []domain.OrganizationType); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OrganizationType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.PaginationQuery) int64); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.PaginationQuery) int); ok {
		r2 = rf(ctx, p)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, common.PaginationQuery) int); ok {
		r3 = rf(ctx, p)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, common.PaginationQuery) error); ok {
		r4 = rf(ctx, p)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Roles provides a mock function with given fields: ctx, orgTypeID
func (_m *OrganizationTypeRepository) Roles(ctx context.Context, orgTypeID int) ([]domain.Role, error) {
	ret := _m.Called(ctx, orgTypeID)

	if len(ret) == 0 {
		panic("no return value specified for Roles")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.Role, error)); ok {
		return rf(ctx, orgTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.Role); ok {
		r0 = rf(ctx, orgTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, orgTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Systems provides a mock function with given fields: ctx, orgTypeID
func (_m *OrganizationTypeRepository) Systems(ctx context.Context, orgTypeID int) ([]domain.System, error) {
	ret := _m.Called(ctx, orgTypeID)

	if len(ret) == 0 {
		panic("no return value specified for Systems")
	}

	var r0 []domain.System
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.System, error)); ok {
		return rf(ctx, orgTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.System); ok {
		r0 = rf(ctx, orgTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.System)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, orgTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *OrganizationTypeRepository) Update(ctx context.Context, id int, m domain.OrganizationType) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.OrganizationType) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrganizationTypeRepository creates a new instance of OrganizationTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationTypeRepository {
	mock := &OrganizationTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
