// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"
	dto "templatev25/internal/http/dto"

	mock "github.com/stretchr/testify/mock"
)

// OrgUserRepository is an autogenerated mock type for the OrgUserRepository type
type OrgUserRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, ou
func (_m *OrgUserRepository) Add(ctx context.Context, ou domain.OrganizationUser) error {
	ret := _m.Called(ctx, ou)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrganizationUser) error); ok {
		r0 = rf(ctx, ou)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByOrgAndUser provides a mock function with given fields: ctx, orgId, userId
func (_m *OrgUserRepository) FindByOrgAndUser(ctx context.Context, orgId int, userId int) (domain.OrganizationUser, error) {
	ret := _m.Called(ctx, orgId, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrgAndUser")
	}

	var r0 domain.OrganizationUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (domain.OrganizationUser, error)); ok {
		return rf(ctx, orgId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) domain.OrganizationUser); ok {
		r0 = rf(ctx, orgId, userId)
	} else {
		r0 = ret.Get(0).(domain.OrganizationUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, orgId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, q
func (_m *OrgUserRepository) List(ctx context.Context, q dto.OrgUserListQuery) ([]domain.OrganizationUser, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.OrganizationUser
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.OrgUserListQuery) ([]domain.OrganizationUser, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.OrgUserListQuery) []domain.OrganizationUser); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OrganizationUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.OrgUserListQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.OrgUserListQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.OrgUserListQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.OrgUserListQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// ListOrgsByUser provides a mock function with given fields: ctx, userId, name, page, size
func (_m *OrgUserRepository) ListOrgsByUser(ctx context.Context, userId int, name string, page int, size int) ([]dto.ResOrguserOrgItem, int64, error) {
	ret := _m.Called(ctx, userId, name, page, size)

	if len(ret) == 0 {
		panic("no return value specified for ListOrgsByUser")
	}

	var r0 []dto.ResOrguserOrgItem
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, int, int) ([]dto.ResOrguserOrgItem, int64, error)); ok {
		return rf(ctx, userId, name, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, int, int) []dto.ResOrguserOrgItem); ok {
		r0 = rf(ctx, userId, name, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ResOrguserOrgItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, int, int) int64); ok {
		r1 = rf(ctx, userId, name, page, size)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, string, int, int) error); ok {
		r2 = rf(ctx, userId, name, page, size)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListUsersByOrg provides a mock function with given fields: ctx, orgId, name, page, size
func (_m *OrgUserRepository) ListUsersByOrg(ctx context.Context, orgId int, name string, page int, size int) ([]dto.ResOrguserUserItem, int64, error) {
	ret := _m.Called(ctx, orgId, name, page, size)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersByOrg")
	}

	var r0 []dto.ResOrguserUserItem
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, int, int) ([]dto.ResOrguserUserItem, int64, error)); ok {
		return rf(ctx, orgId, name, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, int, int) []dto.ResOrguserUserItem); ok {
		r0 = rf(ctx, orgId, name, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ResOrguserUserItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, int, int) int64); ok {
		r1 = rf(ctx, orgId, name, page, size)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, string, int, int) error); ok {
		r2 = rf(ctx, orgId, name, page, size)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// OrgExists provides a mock function with given fields: ctx, orgId
func (_m *OrgUserRepository) OrgExists(ctx context.Context, orgId int) (bool, error) {
	ret := _m.Called(ctx, orgId)

	if len(ret) == 0 {
		panic("no return value specified for OrgExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return rf(ctx, orgId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, orgId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, orgId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: ctx, orgId, userId
func (_m *OrgUserRepository) Remove(ctx context.Context, orgId int, userId int) error {
	ret := _m.Called(ctx, orgId, userId)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, orgId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserExists provides a mock function with given fields: ctx, userId
func (_m *OrgUserRepository) UserExists(ctx context.Context, userId int) (bool, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrgUserRepository creates a new instance of OrgUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrgUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrgUserRepository {
	mock := &OrgUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
