// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"
	dto "templatev25/internal/http/dto"

	mock "github.com/stretchr/testify/mock"
)

// PublicFileRepository is an autogenerated mock type for the PublicFileRepository type
type PublicFileRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, m
func (_m *PublicFileRepository) Create(ctx context.Context, m domain.PublicFile) (domain.PublicFile, error) {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.PublicFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PublicFile) (domain.PublicFile, error)); ok {
		return rf(ctx, m)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PublicFile) domain.PublicFile); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Get(0).(domain.PublicFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PublicFile) error); ok {
		r1 = rf(ctx, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *PublicFileRepository) DeleteByID(ctx context.Context, id int) (domain.PublicFile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 domain.PublicFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.PublicFile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.PublicFile); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.PublicFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PublicFileRepository) GetByID(ctx context.Context, id int) (domain.PublicFile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.PublicFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.PublicFile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.PublicFile); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.PublicFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *PublicFileRepository) GetByName(ctx context.Context, name string) (domain.PublicFile, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 domain.PublicFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.PublicFile, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.PublicFile); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.PublicFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, q
func (_m *PublicFileRepository) List(ctx context.Context, q dto.PublicFileListQuery) ([]domain.PublicFile, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.PublicFile
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.PublicFileListQuery) ([]domain.PublicFile, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.PublicFileListQuery) []domain.PublicFile); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PublicFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.PublicFileListQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.PublicFileListQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.PublicFileListQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.PublicFileListQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// NewPublicFileRepository creates a new instance of PublicFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublicFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PublicFileRepository {
	mock := &PublicFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
