// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"
	dto "templatev25/internal/http/dto"

	mock "github.com/stretchr/testify/mock"
)

// SystemRepository is an autogenerated mock type for the SystemRepository type
type SystemRepository struct {
	mock.Mock
}

// ByID provides a mock function with given fields: ctx, id
func (_m *SystemRepository) ByID(ctx context.Context, id int) (domain.System, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 domain.System
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.System, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.System); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.System)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, m
func (_m *SystemRepository) Create(ctx context.Context, m domain.System) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.System) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SystemRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveModuleCount provides a mock function with given fields: uctx, id
func (_m *SystemRepository) GetActiveModuleCount(uctx context.Context, id int) int64 {
	ret := _m.Called(uctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveModuleCount")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(uctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetActiveRoleCount provides a mock function with given fields: uctx, id
func (_m *SystemRepository) GetActiveRoleCount(uctx context.Context, id int) int64 {
	ret := _m.Called(uctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveRoleCount")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(uctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// List provides a mock function with given fields: ctx, q
func (_m *SystemRepository) List(ctx context.Context, q dto.SystemListQuery) ([]domain.System, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.System
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SystemListQuery) ([]domain.System, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SystemListQuery) []domain.System); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.System)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SystemListQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.SystemListQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.SystemListQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.SystemListQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *SystemRepository) Update(ctx context.Context, id int, m domain.System) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.System) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSystemRepository creates a new instance of SystemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSystemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SystemRepository {
	mock := &SystemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
