// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	common "git.gerege.mn/backend-packages/common"

	domain "templatev25/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TerminalRepository is an autogenerated mock type for the TerminalRepository type
type TerminalRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, m
func (_m *TerminalRepository) Create(ctx context.Context, m domain.Terminal) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Terminal) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSoft provides a mock function with given fields: uctx, id
func (_m *TerminalRepository) DeleteSoft(uctx context.Context, id int) error {
	ret := _m.Called(uctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSoft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(uctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, p
func (_m *TerminalRepository) List(ctx context.Context, p common.PaginationQuery) ([]domain.Terminal, int64, int, int, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Terminal
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) ([]domain.Terminal, int64, int, int, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.PaginationQuery) []domain.Terminal); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Terminal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.PaginationQuery) int64); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.PaginationQuery) int); ok {
		r2 = rf(ctx, p)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, common.PaginationQuery) int); ok {
		r3 = rf(ctx, p)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, common.PaginationQuery) error); ok {
		r4 = rf(ctx, p)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// Update provides a mock function with given fields: ctx, id, m
func (_m *TerminalRepository) Update(ctx context.Context, id int, m domain.Terminal) error {
	ret := _m.Called(ctx, id, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, domain.Terminal) error); ok {
		r0 = rf(ctx, id, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTerminalRepository creates a new instance of TerminalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerminalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerminalRepository {
	mock := &TerminalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
