// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "templatev25/internal/domain"
	dto "templatev25/internal/http/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserRoleRepository is an autogenerated mock type for the UserRoleRepository type
type UserRoleRepository struct {
	mock.Mock
}

// AddRolesToUser provides a mock function with given fields: ctx, userID, roleIDs
func (_m *UserRoleRepository) AddRolesToUser(ctx context.Context, userID int, roleIDs []int) error {
	ret := _m.Called(ctx, userID, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddRolesToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, userID, roleIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUsersToRole provides a mock function with given fields: ctx, roleID, userIDs
func (_m *UserRoleRepository) AddUsersToRole(ctx context.Context, roleID int, userIDs []int) error {
	ret := _m.Called(ctx, roleID, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddUsersToRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []int) error); ok {
		r0 = rf(ctx, roleID, userIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: ctx, userID, roleID
func (_m *UserRoleRepository) Remove(ctx context.Context, userID int, roleID int) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RolesByUser provides a mock function with given fields: ctx, q
func (_m *UserRoleRepository) RolesByUser(ctx context.Context, q dto.UserRoleRolesQuery) ([]domain.UserRole, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for RolesByUser")
	}

	var r0 []domain.UserRole
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserRoleRolesQuery) ([]domain.UserRole, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserRoleRolesQuery) []domain.UserRole); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserRoleRolesQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.UserRoleRolesQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.UserRoleRolesQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.UserRoleRolesQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// UsersByRole provides a mock function with given fields: ctx, q
func (_m *UserRoleRepository) UsersByRole(ctx context.Context, q dto.UserRoleUsersQuery) ([]domain.UserRole, int64, int, int, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for UsersByRole")
	}

	var r0 []domain.UserRole
	var r1 int64
	var r2 int
	var r3 int
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserRoleUsersQuery) ([]domain.UserRole, int64, int, int, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserRoleUsersQuery) []domain.UserRole); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserRoleUsersQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.UserRoleUsersQuery) int); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, dto.UserRoleUsersQuery) int); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Get(3).(int)
	}

	if rf, ok := ret.Get(4).(func(context.Context, dto.UserRoleUsersQuery) error); ok {
		r4 = rf(ctx, q)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// NewUserRoleRepository creates a new instance of UserRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRoleRepository {
	mock := &UserRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
