// Package docs provides Swagger documentation
//
// File: docs_test.go
// Description: Unit tests for docs package
package docs

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestSwaggerInfo tests that SwaggerInfo is properly initialized
func TestSwaggerInfo(t *testing.T) {
	// SwaggerInfo contains the API documentation metadata
	assert.NotNil(t, SwaggerInfo)
	assert.NotEmpty(t, SwaggerInfo.Title)
	assert.NotEmpty(t, SwaggerInfo.Version)
}

// TestDocsPackage documents the docs package
func TestDocsPackage(t *testing.T) {
	// This package is auto-generated by swag init command
	// It contains:
	// - swagger.json: OpenAPI 3.0 specification
	// - swagger.yaml: OpenAPI 3.0 specification (YAML)
	// - docs.go: Go code with embedded documentation

	t.Log("docs package provides Swagger/OpenAPI documentation")
}

// TestSwaggerGeneration documents swagger generation
func TestSwaggerGeneration(t *testing.T) {
	// To regenerate swagger docs:
	// 1. Install swag: go install github.com/swaggo/swag/cmd/swag@latest
	// 2. Run: swag init -g cmd/server/main.go -o docs/

	// Swagger annotations are in:
	// - cmd/server/main.go (API metadata)
	// - internal/http/handlers/*.go (endpoint documentation)

	commands := []string{
		"go install github.com/swaggo/swag/cmd/swag@latest",
		"swag init -g cmd/server/main.go -o docs/",
	}

	for _, cmd := range commands {
		t.Logf("Command: %s", cmd)
	}
}
