// Original System data structure
export const menuList: App.Menu[] = [
  {
    id: 7,
    code: 'ADMIN',
    name: 'Админ систем',
    description: 'Админ систем',
    icon: 'i-lucide-monitor-cog',
    path: '',
    sequence: 1,
    children: [
      {
        id: 1,
        code: 'core',
        name: 'Үндсэн',
        description: 'Үндсэн системийн модуль групп',
        children: [
          {
            id: 16,
            code: 'ADMIN-DASHBOARD',
            name: 'Хянах самбар',
            description: 'Админ хянах самбар',
            icon: 'i-lucide-monitor',
            path: '/admin/dashboard',
            sequence: 1,
            is_active: true,
            key: '',
          },
          {
            id: 17,
            code: 'ADMIN-ORGTYPE',
            name: 'Байгууллагын төрөл',
            description: 'Байгууллагын төрөл',
            icon: 'i-lucide-layers-3',
            path: '/admin/organization-type',
            sequence: 2,
            is_active: true,
            key: '',
          },
          {
            id: 12,
            code: 'ADMIN-ORG',
            name: 'Байгууллага',
            description: 'Байгууллага',
            icon: 'i-lucide-building-2',
            path: '/admin/organization',
            sequence: 3,
            is_active: true,
            key: '',
          },
          {
            id: 7,
            code: 'ADMIN-SYSTEM',
            name: 'Систем',
            description: 'Систем',
            icon: 'i-lucide-monitor-cog',
            path: '/admin/system',
            sequence: 4,
            is_active: true,
            key: '',
          },
          {
            id: 8,
            code: 'ADMIN-MODULE',
            name: 'Модул',
            description: 'Модул',
            icon: 'i-lucide-menu',
            path: '/admin/module',
            sequence: 6,
            is_active: true,
            key: '',
          },
          {
            id: 1231,
            code: 'ADMIN-ACTION',
            name: 'Үйлдэл',
            description: 'Үйлдэл',
            icon: 'i-lucide-menu',
            path: '/admin/action',
            sequence: 9,
            is_active: true,
            key: '',
          },
          {
            id: 135,
            code: 'ADMIN-menu',
            name: 'Цэс',
            description: 'Цэс',
            icon: 'i-lucide-menu',
            path: '/admin/menu',
            sequence: 6,
            is_active: true,
            key: '',
          },
          {
            id: 11,
            code: 'ADMIN-PERMISSION',
            name: 'Зөвшөөрөл',
            description: 'Зөвшөөрөл',
            icon: 'i-lucide-shield-check',
            path: '/admin/permission',
            sequence: 7,
            is_active: true,
            key: '',
          },
        ],
        key: '',
        sequence: 0,
      },
      {
        id: 8,
        code: 'core_bla',
        name: 'Bla bla',
        description: '',
        children: [
          {
            id: 10,
            code: 'ADMIN-ROLE',
            name: 'Хэрэглэгчийн эрх',
            description: 'Хэрэглэгчийн эрх',
            icon: 'i-lucide-shield-half',
            path: '/admin/role',
            sequence: 8,
            is_active: true,
            key: '',
          },
          {
            id: 13,
            code: 'ADMIN-USER',
            name: 'Хэрэглэгч',
            description: 'Хэрэглэгч',
            icon: 'i-lucide-users',
            path: '/admin/user',
            sequence: 9,
            is_active: true,
            key: '',
          },
        ],
        key: '',
        sequence: 0,
      },
    ],
    key: '',
  },
  {
    id: 10,
    code: 'TPAY',
    name: 'Гэрэгэ хэтэвч',
    description: 'Гэрэгэ төлбөрийн систем',
    icon: 'i-lucide-wallet',
    path: '',
    sequence: 2,
    children: [
      {
        id: 4,
        code: 'c_core',
        name: 'Үндсэн',
        description: 'Үндсэн',
        children: [
          {
            id: 18,
            code: 'TPAY-DASHBOARD',
            name: 'Хянах самбар',
            description: 'T-Pay хянах самбар',
            icon: '',
            path: '/tpay/dashboard',
            sequence: 301,
            is_active: true,
            key: '',
          },
          {
            id: 23,
            code: 'TPAY-BALANCE',
            name: 'Баланс',
            description: 'TPay баланс',
            icon: '',
            path: '/tpay/balance',
            sequence: 303,
            is_active: true,
            key: '',
          },
          {
            id: 22,
            code: 'TPAY-TRX',
            name: 'Гүйлгээ',
            description: 'TPay гүйлгээ',
            icon: 'i-lucide-arrow-left-right',
            path: '/tpay/transaction',
            sequence: 304,
            is_active: true,
            key: '',
          },
          {
            id: 21,
            code: 'TPAY-WALLET',
            name: 'Хэтэвч',
            description: 'TPay хэтэвч',
            icon: '',
            path: '/tpay/wallet',
            sequence: 305,
            is_active: true,
            key: '',
          },
          {
            id: 25,
            code: 'TPAY-ROLE',
            name: 'Дүр',
            description: 'ТPay системийн дүрүүд',
            icon: '',
            path: '/tpay/role',
            sequence: 306,
            is_active: true,
            key: '',
          },
          {
            id: 29,
            code: 'TPAY-USERS',
            name: 'Хэрэглэгчид',
            description: '',
            icon: '',
            path: '/tpay/users',
            sequence: 389,
            is_active: true,
            key: '',
          },
          {
            id: 30,
            code: 'TPAY-PRODUCTS',
            name: 'Бүтээгдэхүүний каталог',
            description: '',
            icon: '',
            path: '/tpay/products',
            sequence: 398,
            is_active: true,
            key: '',
          },
        ],
        key: '',
        sequence: 0,
      },
    ],
    key: '',
  },
  {
    id: 9,
    code: 'GRGA',
    name: 'Гэрэгэ апп',
    description: 'Гэрэгэ Апп',
    icon: 'i-lucide-smartphone',
    path: '',
    sequence: 3,
    children: [
      {
        id: 3,
        code: 'b_core',
        name: 'Үндсэн',
        description: 'Үндсэн',
        children: [
          {
            id: 19,
            code: 'GRGA-DASHBOARD',
            name: 'Хянах самбар',
            description: 'Гэрэгэ апп хянах самбар',
            icon: 'i-lucide-monitor',
            path: '/app/dashboard',
            sequence: 101,
            is_active: true,
            key: '',
          },
          {
            id: 14,
            code: 'GRGA-ICON',
            name: 'Апп айкон',
            description: 'Апп айкон',
            icon: 'i-lucide-grid',
            path: '/app/icon',
            sequence: 102,
            is_active: true,
            key: '',
          },
          {
            id: 26,
            code: 'GRGA-ROLE',
            name: 'Дүр',
            description: 'Гэрэгэ аппын дүрүүд',
            icon: '',
            path: '/app/role',
            sequence: 103,
            is_active: true,
            key: '',
          },
        ],
        key: '',
        sequence: 0,
      },
    ],
    key: '',
  },
  {
    id: 8,
    code: 'GRGB',
    name: 'Гэрэгэ бизнес',
    description: 'Гэрэгэ бизнес',
    icon: 'i-lucide-briefcase-business',
    path: '',
    sequence: 4,
    children: [
      {
        id: 2,
        code: 'a_core',
        name: 'Үндсэн',
        description: 'Үндсэн',
        children: [
          {
            id: 20,
            code: 'GRGB-DASHBOARD',
            name: 'Хянах самбар',
            description: 'Гэрэгэ бизнес хянах самбар',
            icon: '',
            path: '/business/dashboard',
            sequence: 201,
            is_active: true,
            key: '',
          },
          {
            id: 15,
            code: 'GRGB-ICON',
            name: 'Апп айкон',
            description: 'Апп айкон',
            icon: 'i-lucide-grid',
            path: '/business/icon',
            sequence: 202,
            is_active: true,
            key: '',
          },
          {
            id: 27,
            code: 'GRGB-ROLE',
            name: 'Дүр',
            description: 'Гэрэгэ бизнесийн дүрүүд',
            icon: '',
            path: '/business/role',
            sequence: 203,
            is_active: true,
            key: '',
          },
          {
            id: 24,
            code: 'GRGB-AGENTS',
            name: 'Агент',
            description: 'Бизнес агентууд',
            icon: '',
            path: '/business/agent',
            sequence: 204,
            is_active: true,
            key: '',
          },
        ],
        key: '',
        sequence: 0,
      },
    ],
    key: '',
  },
]

// Convert System structure to Menu tree
